In [ ]:
# 安装依赖
pip install torch torchvision --index-url https://download.pytorch.org/whl/cu126  
pip install transformers==5.6.0 accelerate==1.7.0 trl  # 必选
pip install peft bitsandbytes sentencepiece sentence-transformers  # 可选
pip install deepspeed  # Linux only

In [ ]:
# 训练启动命令：模型并行
python training_for_fft.py

# 训练启动命令：数据并行(单机多卡)
torchrun --nnodes=1 --nproc_per_node=8 training_for_fft.py

In [1]:
import os
import sys
import warnings; warnings.filterwarnings("ignore")
import json
import numpy as np
import pandas as pd
import torch as th
import transformers
import accelerate
import trl

from pprint import pp
from datasets import (load_dataset, load_from_disk, Dataset)
from transformers import (AutoTokenizer, AutoModelForCausalLM)
from trl import (SFTConfig, SFTTrainer)

if sys.platform == "linux":
    import deepspeed
    import torch_npu as th_npu

In [2]:
device = th.device('cuda' if th.cuda.is_available() else 'cpu')
# device = th.device("npu" if th.npu.is_available() else "cpu")
device_count = th.cuda.device_count() if th.cuda.is_available() else 0
# device_count = th.npu.device_count() if th.npu.is_available() else 0
device_name = th.cuda.get_device_name(0) if th.cuda.is_available() else 'cpu'
print(f'torch version = {th.__version__}')
print(f'cuda version = {th.version.cuda}')
print(f'device = {device}')
print(f'device_count = {device_count}')
print(f'device_name = {device_name}')
print(f'transformers version = {transformers.__version__}')
print(f'accelerate version = {accelerate.__version__}')
print(f'trl version = {trl.__version__}')

torch version = 2.12.0+cu126
cuda version = 12.6
device = cuda
device_count = 1
device_name = NVIDIA GeForce GTX 1080 Ti
transformers version = 5.6.0
accelerate version = 1.7.0
trl version = 0.24.0
peft version = 0.18.1

In [3]:
path_project = "C:/my_project/MyGit/Machine-Learning-Column/explore_on_llm/"
path_data = os.path.join(os.path.dirname(os.path.dirname(path_project)), "data")
path_model = "F:/LLM"
path_output = os.path.join(path_model, "output")

os.makedirs(path_data, exist_ok=True)
os.makedirs(path_model, exist_ok=True)
os.makedirs(path_output, exist_ok=True)

## step-1: 数据源

In [4]:
filename = "identity.json"  # llama-factory 官方样例

In [5]:
dataset = load_dataset(
    path="json",
    data_files=os.path.join(path_data, filename),
    split="all"
)

In [6]:
dataset = dataset.train_test_split(test_size=0.1, shuffle=True, seed=0)
train_dataset, eval_dataset = dataset["train"], dataset["test"]

In [7]:
pp(train_dataset[0])

{'instruction': '你好',
 'input': '',
 'output': '您好，我是 Coco，一个由 Lukas 开发的 AI 助手，很高兴认识您。请问我能为您做些什么？'}

## step-2: tokenizer

In [8]:
checkpoint = "Qwen/Qwen3.5-0.8B"

In [9]:
tokenizer = AutoTokenizer.from_pretrained(
    pretrained_model_name_or_path=os.path.join(path_model, checkpoint),
    cache_dir=path_model,
    force_download=False,
    local_files_only=True
)

In [10]:
if tokenizer.pad_token_id is None:
    tokenizer.pad_token_id = tokenizer.eos_token_id
    print('pad_token 为 None，已设为 eos_token')

In [11]:
pp(f"eos_token = {tokenizer.eos_token}")
pp(f"pad_token = {tokenizer.pad_token}")
pp(f"padding_side = {tokenizer.padding_side}")

'eos_token = <|im_end|>'
'pad_token = <|endoftext|>'
'padding_side = right'

## step-3: 量化参数（可选）

In [ ]:
# config_bnb = BitsAndBytesConfig(
#     load_in_4bit=True,
#     bnb_4bit_quant_type="nf4",
#     bnb_4bit_compute_dtype=th.bfloat16,
#     bnb_4bit_use_double_quant=True
# )  # QLoRA

## step-4: 载入基模

In [13]:
base_model = AutoModelForCausalLM.from_pretrained(
    pretrained_model_name_or_path=os.path.join(path_model, checkpoint),
    cache_dir=path_model,
    device_map="auto",  # deepspeed 场景下删除
    dtype=th.bfloat16,
    attn_implementation="sdpa",  # flash_attention_2, sdpa
    force_download=False,
    local_files_only=True,
    trust_remote_code=True,
    low_cpu_mem_usage=True,
    # quantization_config=config_bnb,
)

[transformers] The fast path is not available because one of the required library is not installed. Falling back to torch implementation. To install follow https://github.com/fla-org/flash-linear-attention#installation and https://github.com/Dao-AILab/causal-conv1d
Loading weights: 100%|██████████| 320/320 [00:00<00:00, 399.57it/s]

In [14]:
tokenizer_size = len(tokenizer)
embedding_size = base_model.config.vocab_size
if tokenizer_size > embedding_size:
    base_model.resize_token_embeddings(tokenizer_size)

In [ ]:
for i, (name, parm) in enumerate(base_model.named_parameters()):
    print(f"{i}  name: {name};  shape: {parm.shape};  dtype: {parm.dtype};  device: {parm.device}")

In [16]:
base_model.gradient_checkpointing_enable(
    gradient_checkpointing_kwargs={"use_reentrant": False}
)
base_model.enable_input_require_grads()
base_model.config.use_cache = False

In [ ]:
# deepspeed 场景下删除
if th.cuda.device_count() > 1:
    base_model.is_parallelizable = True
    base_model.model_parallel = True

In [17]:
allocated_memory = th.cuda.memory_allocated()
cached_memory = th.cuda.memory_cached()
print(f"已分配的GPU内存：{allocated_memory / 1024**3:.2f}G, 已缓存的GPU内存：{cached_memory / 1024**3:.2f}G")

已分配的GPU内存：1.40G, 已缓存的GPU内存：1.89G

## step-5: 模型参数

In [ ]:
with open("./config/ds_z2_config.json", "r", encoding="utf-8") as f:
    deepspeed_config = json.load(f)

In [18]:
train_args = SFTConfig(
    output_dir=os.path.join(path_output, "model_fft"),
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=2,
    gradient_checkpointing=True,
    optim="adamw_torch",
    learning_rate=0.00002,
    warmup_steps=0.03,  # 预热
    lr_scheduler_type="cosine_with_min_lr",  # 退火
    lr_scheduler_kwargs={"min_lr_rate": 0.1},  # 退火参数
    logging_strategy="epoch",
    save_strategy="epoch",
    eval_strategy="epoch",
    metric_for_best_model="eval_loss",
    load_best_model_at_end=True,
    greater_is_better=False,
    dataset_text_field="text",
    packing=False,  # 需要 attn_implementation="flash_attention_2"
    save_total_limit=1,
    save_only_model=False,
    
    # === deepspeed 场景 ===
    # deepspeed=deepspeed_config,
    # ddp_find_unused_parameters=False
)

## step-6: LoRA参数

不涉及

## step-7: 整理函数

In [19]:
system_prompt = "You are a helpful assistant."

In [20]:
def apply_sft_template(sample):
    """数据集整理函数，适配原始数据集格式，这里的样例是alpaca结构
    
    """
    user_prompt = sample["instruction"] + "\n" + sample["input"]
    assistant_prompt = sample["output"]
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
        {"role": "assistant", "content": assistant_prompt}
    ]
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False,
        enable_thinking=False,  # 禁用思考
    )
    sample["text"] = text
    return sample

In [21]:
dataset = dataset.map(apply_sft_template)

In [22]:
train_dataset = dataset["train"]
test_dataset = dataset["test"]

## step-8: 模型训练

In [23]:
trainer = SFTTrainer(
    model=base_model,
    processing_class=tokenizer,
    args=train_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
)

In [24]:
training_result = trainer.train()

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 248046, 'pad_token_id': 248044}.

Writing model shards: 100%|██████████| 1/1 [00:03<00:00,  3.86s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.24s/it]
Writing model shards: 100%|██████████| 1/1 [00:04<00:00,  4.66s/it]
[transformers] There were missing keys in the checkpoint model loaded: ['model.embed_tokens.weight', 'model.layers.0.linear_attn.dt_bias', 'model.layers.0.linear_attn.A_log', 'model.layers.0.linear_attn.conv1d.weight', 'model.layers.0.linear_attn.norm.weight', 'model.layers.0.linear_attn.out_proj.weight', 'model.layers.0.linear_attn.in_proj_qkv.weight', 'model.layers.0.linear_attn.in_proj_z.weight', 'model.layers.0.linear_attn.in_proj_b.weight', 'model.layers.0.linear_attn.in_proj_a.weight', 'model.layers.0.mlp.gate_proj.weight', 'model.layers.0.mlp.up_proj.weight', 'model.layers.0.mlp.down_proj.weight', 'model.layers.0.input_layernorm.weight', 'model.layers.0.post_attention_layernorm.weight', 'model.layers.1.linear_attn.dt_bias', 'model.layers.1.linear_attn.A_log', 'model.layers.1.linear_attn.conv1d.weight', 'model.layers.1.linear_attn.norm.weight', 'model.layers.1.linear_attn.out_proj.weight', 'model.layers.1.linear_attn.in_proj_qkv.weight', 'model.layers.1.linear_attn.in_proj_z.weight', 'model.layers.1.linear_attn.in_proj_b.weight', 'model.layers.1.linear_attn.in_proj_a.weight', 'model.layers.1.mlp.gate_proj.weight', 'model.layers.1.mlp.up_proj.weight', 'model.layers.1.mlp.down_proj.weight', 'model.layers.1.input_layernorm.weight', 'model.layers.1.post_attention_layernorm.weight', 'model.layers.2.linear_attn.dt_bias', 'model.layers.2.linear_attn.A_log', 'model.layers.2.linear_attn.conv1d.weight', 'model.layers.2.linear_attn.norm.weight', 'model.layers.2.linear_attn.out_proj.weight', 'model.layers.2.linear_attn.in_proj_qkv.weight', 'model.layers.2.linear_attn.in_proj_z.weight', 'model.layers.2.linear_attn.in_proj_b.weight', 'model.layers.2.linear_attn.in_proj_a.weight', 'model.layers.2.mlp.gate_proj.weight', 'model.layers.2.mlp.up_proj.weight', 'model.layers.2.mlp.down_proj.weight', 'model.layers.2.input_layernorm.weight', 'model.layers.2.post_attention_layernorm.weight', 'model.layers.3.self_attn.q_proj.weight', 'model.layers.3.self_attn.k_proj.weight', 'model.layers.3.self_attn.v_proj.weight', 'model.layers.3.self_attn.o_proj.weight', 'model.layers.3.self_attn.q_norm.weight', 'model.layers.3.self_attn.k_norm.weight', 'model.layers.3.mlp.gate_proj.weight', 'model.layers.3.mlp.up_proj.weight', 'model.layers.3.mlp.down_proj.weight', 'model.layers.3.input_layernorm.weight', 'model.layers.3.post_attention_layernorm.weight', 'model.layers.4.linear_attn.dt_bias', 'model.layers.4.linear_attn.A_log', 'model.layers.4.linear_attn.conv1d.weight', 'model.layers.4.linear_attn.norm.weight', 'model.layers.4.linear_attn.out_proj.weight', 'model.layers.4.linear_attn.in_proj_qkv.weight', 'model.layers.4.linear_attn.in_proj_z.weight', 'model.layers.4.linear_attn.in_proj_b.weight', 'model.layers.4.linear_attn.in_proj_a.weight', 'model.layers.4.mlp.gate_proj.weight', 'model.layers.4.mlp.up_proj.weight', 'model.layers.4.mlp.down_proj.weight', 'model.layers.4.input_layernorm.weight', 'model.layers.4.post_attention_layernorm.weight', 'model.layers.5.linear_attn.dt_bias', 'model.layers.5.linear_attn.A_log', 'model.layers.5.linear_attn.conv1d.weight', 'model.layers.5.linear_attn.norm.weight', 'model.layers.5.linear_attn.out_proj.weight', 'model.layers.5.linear_attn.in_proj_qkv.weight', 'model.layers.5.linear_attn.in_proj_z.weight', 'model.layers.5.linear_attn.in_proj_b.weight', 'model.layers.5.linear_attn.in_proj_a.weight', 'model.layers.5.mlp.gate_proj.weight', 'model.layers.5.mlp.up_proj.weight', 'model.layers.5.mlp.down_proj.weight', 'model.layers.5.input_layernorm.weight', 'model.layers.5.post_attention_layernorm.weight', 'model.layers.6.linear_attn.dt_bias', 'model.layers.6.linear_attn.A_log', 'model.layers.6.linear_attn.conv1d.weight', 'model.layers.6.linear_attn.norm.weight', 'model.layers.6.linear_attn.out_proj.weight', 'model.layers.6.linear_attn.in_proj_qkv.weight', 'model.layers.6.linear_attn.in_proj_z.weight', 'model.layers.6.linear_attn.in_proj_b.weight', 'model.layers.6.linear_attn.in_proj_a.weight', 'model.layers.6.mlp.gate_proj.weight', 'model.layers.6.mlp.up_proj.weight', 'model.layers.6.mlp.down_proj.weight', 'model.layers.6.input_layernorm.weight', 'model.layers.6.post_attention_layernorm.weight', 'model.layers.7.self_attn.q_proj.weight', 'model.layers.7.self_attn.k_proj.weight', 'model.layers.7.self_attn.v_proj.weight', 'model.layers.7.self_attn.o_proj.weight', 'model.layers.7.self_attn.q_norm.weight', 'model.layers.7.self_attn.k_norm.weight', 'model.layers.7.mlp.gate_proj.weight', 'model.layers.7.mlp.up_proj.weight', 'model.layers.7.mlp.down_proj.weight', 'model.layers.7.input_layernorm.weight', 'model.layers.7.post_attention_layernorm.weight', 'model.layers.8.linear_attn.dt_bias', 'model.layers.8.linear_attn.A_log', 'model.layers.8.linear_attn.conv1d.weight', 'model.layers.8.linear_attn.norm.weight', 'model.layers.8.linear_attn.out_proj.weight', 'model.layers.8.linear_attn.in_proj_qkv.weight', 'model.layers.8.linear_attn.in_proj_z.weight', 'model.layers.8.linear_attn.in_proj_b.weight', 'model.layers.8.linear_attn.in_proj_a.weight', 'model.layers.8.mlp.gate_proj.weight', 'model.layers.8.mlp.up_proj.weight', 'model.layers.8.mlp.down_proj.weight', 'model.layers.8.input_layernorm.weight', 'model.layers.8.post_attention_layernorm.weight', 'model.layers.9.linear_attn.dt_bias', 'model.layers.9.linear_attn.A_log', 'model.layers.9.linear_attn.conv1d.weight', 'model.layers.9.linear_attn.norm.weight', 'model.layers.9.linear_attn.out_proj.weight', 'model.layers.9.linear_attn.in_proj_qkv.weight', 'model.layers.9.linear_attn.in_proj_z.weight', 'model.layers.9.linear_attn.in_proj_b.weight', 'model.layers.9.linear_attn.in_proj_a.weight', 'model.layers.9.mlp.gate_proj.weight', 'model.layers.9.mlp.up_proj.weight', 'model.layers.9.mlp.down_proj.weight', 'model.layers.9.input_layernorm.weight', 'model.layers.9.post_attention_layernorm.weight', 'model.layers.10.linear_attn.dt_bias', 'model.layers.10.linear_attn.A_log', 'model.layers.10.linear_attn.conv1d.weight', 'model.layers.10.linear_attn.norm.weight', 'model.layers.10.linear_attn.out_proj.weight', 'model.layers.10.linear_attn.in_proj_qkv.weight', 'model.layers.10.linear_attn.in_proj_z.weight', 'model.layers.10.linear_attn.in_proj_b.weight', 'model.layers.10.linear_attn.in_proj_a.weight', 'model.layers.10.mlp.gate_proj.weight', 'model.layers.10.mlp.up_proj.weight', 'model.layers.10.mlp.down_proj.weight', 'model.layers.10.input_layernorm.weight', 'model.layers.10.post_attention_layernorm.weight', 'model.layers.11.self_attn.q_proj.weight', 'model.layers.11.self_attn.k_proj.weight', 'model.layers.11.self_attn.v_proj.weight', 'model.layers.11.self_attn.o_proj.weight', 'model.layers.11.self_attn.q_norm.weight', 'model.layers.11.self_attn.k_norm.weight', 'model.layers.11.mlp.gate_proj.weight', 'model.layers.11.mlp.up_proj.weight', 'model.layers.11.mlp.down_proj.weight', 'model.layers.11.input_layernorm.weight', 'model.layers.11.post_attention_layernorm.weight', 'model.layers.12.linear_attn.dt_bias', 'model.layers.12.linear_attn.A_log', 'model.layers.12.linear_attn.conv1d.weight', 'model.layers.12.linear_attn.norm.weight', 'model.layers.12.linear_attn.out_proj.weight', 'model.layers.12.linear_attn.in_proj_qkv.weight', 'model.layers.12.linear_attn.in_proj_z.weight', 'model.layers.12.linear_attn.in_proj_b.weight', 'model.layers.12.linear_attn.in_proj_a.weight', 'model.layers.12.mlp.gate_proj.weight', 'model.layers.12.mlp.up_proj.weight', 'model.layers.12.mlp.down_proj.weight', 'model.layers.12.input_layernorm.weight', 'model.layers.12.post_attention_layernorm.weight', 'model.layers.13.linear_attn.dt_bias', 'model.layers.13.linear_attn.A_log', 'model.layers.13.linear_attn.conv1d.weight', 'model.layers.13.linear_attn.norm.weight', 'model.layers.13.linear_attn.out_proj.weight', 'model.layers.13.linear_attn.in_proj_qkv.weight', 'model.layers.13.linear_attn.in_proj_z.weight', 'model.layers.13.linear_attn.in_proj_b.weight', 'model.layers.13.linear_attn.in_proj_a.weight', 'model.layers.13.mlp.gate_proj.weight', 'model.layers.13.mlp.up_proj.weight', 'model.layers.13.mlp.down_proj.weight', 'model.layers.13.input_layernorm.weight', 'model.layers.13.post_attention_layernorm.weight', 'model.layers.14.linear_attn.dt_bias', 'model.layers.14.linear_attn.A_log', 'model.layers.14.linear_attn.conv1d.weight', 'model.layers.14.linear_attn.norm.weight', 'model.layers.14.linear_attn.out_proj.weight', 'model.layers.14.linear_attn.in_proj_qkv.weight', 'model.layers.14.linear_attn.in_proj_z.weight', 'model.layers.14.linear_attn.in_proj_b.weight', 'model.layers.14.linear_attn.in_proj_a.weight', 'model.layers.14.mlp.gate_proj.weight', 'model.layers.14.mlp.up_proj.weight', 'model.layers.14.mlp.down_proj.weight', 'model.layers.14.input_layernorm.weight', 'model.layers.14.post_attention_layernorm.weight', 'model.layers.15.self_attn.q_proj.weight', 'model.layers.15.self_attn.k_proj.weight', 'model.layers.15.self_attn.v_proj.weight', 'model.layers.15.self_attn.o_proj.weight', 'model.layers.15.self_attn.q_norm.weight', 'model.layers.15.self_attn.k_norm.weight', 'model.layers.15.mlp.gate_proj.weight', 'model.layers.15.mlp.up_proj.weight', 'model.layers.15.mlp.down_proj.weight', 'model.layers.15.input_layernorm.weight', 'model.layers.15.post_attention_layernorm.weight', 'model.layers.16.linear_attn.dt_bias', 'model.layers.16.linear_attn.A_log', 'model.layers.16.linear_attn.conv1d.weight', 'model.layers.16.linear_attn.norm.weight', 'model.layers.16.linear_attn.out_proj.weight', 'model.layers.16.linear_attn.in_proj_qkv.weight', 'model.layers.16.linear_attn.in_proj_z.weight', 'model.layers.16.linear_attn.in_proj_b.weight', 'model.layers.16.linear_attn.in_proj_a.weight', 'model.layers.16.mlp.gate_proj.weight', 'model.layers.16.mlp.up_proj.weight', 'model.layers.16.mlp.down_proj.weight', 'model.layers.16.input_layernorm.weight', 'model.layers.16.post_attention_layernorm.weight', 'model.layers.17.linear_attn.dt_bias', 'model.layers.17.linear_attn.A_log', 'model.layers.17.linear_attn.conv1d.weight', 'model.layers.17.linear_attn.norm.weight', 'model.layers.17.linear_attn.out_proj.weight', 'model.layers.17.linear_attn.in_proj_qkv.weight', 'model.layers.17.linear_attn.in_proj_z.weight', 'model.layers.17.linear_attn.in_proj_b.weight', 'model.layers.17.linear_attn.in_proj_a.weight', 'model.layers.17.mlp.gate_proj.weight', 'model.layers.17.mlp.up_proj.weight', 'model.layers.17.mlp.down_proj.weight', 'model.layers.17.input_layernorm.weight', 'model.layers.17.post_attention_layernorm.weight', 'model.layers.18.linear_attn.dt_bias', 'model.layers.18.linear_attn.A_log', 'model.layers.18.linear_attn.conv1d.weight', 'model.layers.18.linear_attn.norm.weight', 'model.layers.18.linear_attn.out_proj.weight', 'model.layers.18.linear_attn.in_proj_qkv.weight', 'model.layers.18.linear_attn.in_proj_z.weight', 'model.layers.18.linear_attn.in_proj_b.weight', 'model.layers.18.linear_attn.in_proj_a.weight', 'model.layers.18.mlp.gate_proj.weight', 'model.layers.18.mlp.up_proj.weight', 'model.layers.18.mlp.down_proj.weight', 'model.layers.18.input_layernorm.weight', 'model.layers.18.post_attention_layernorm.weight', 'model.layers.19.self_attn.q_proj.weight', 'model.layers.19.self_attn.k_proj.weight', 'model.layers.19.self_attn.v_proj.weight', 'model.layers.19.self_attn.o_proj.weight', 'model.layers.19.self_attn.q_norm.weight', 'model.layers.19.self_attn.k_norm.weight', 'model.layers.19.mlp.gate_proj.weight', 'model.layers.19.mlp.up_proj.weight', 'model.layers.19.mlp.down_proj.weight', 'model.layers.19.input_layernorm.weight', 'model.layers.19.post_attention_layernorm.weight', 'model.layers.20.linear_attn.dt_bias', 'model.layers.20.linear_attn.A_log', 'model.layers.20.linear_attn.conv1d.weight', 'model.layers.20.linear_attn.norm.weight', 'model.layers.20.linear_attn.out_proj.weight', 'model.layers.20.linear_attn.in_proj_qkv.weight', 'model.layers.20.linear_attn.in_proj_z.weight', 'model.layers.20.linear_attn.in_proj_b.weight', 'model.layers.20.linear_attn.in_proj_a.weight', 'model.layers.20.mlp.gate_proj.weight', 'model.layers.20.mlp.up_proj.weight', 'model.layers.20.mlp.down_proj.weight', 'model.layers.20.input_layernorm.weight', 'model.layers.20.post_attention_layernorm.weight', 'model.layers.21.linear_attn.dt_bias', 'model.layers.21.linear_attn.A_log', 'model.layers.21.linear_attn.conv1d.weight', 'model.layers.21.linear_attn.norm.weight', 'model.layers.21.linear_attn.out_proj.weight', 'model.layers.21.linear_attn.in_proj_qkv.weight', 'model.layers.21.linear_attn.in_proj_z.weight', 'model.layers.21.linear_attn.in_proj_b.weight', 'model.layers.21.linear_attn.in_proj_a.weight', 'model.layers.21.mlp.gate_proj.weight', 'model.layers.21.mlp.up_proj.weight', 'model.layers.21.mlp.down_proj.weight', 'model.layers.21.input_layernorm.weight', 'model.layers.21.post_attention_layernorm.weight', 'model.layers.22.linear_attn.dt_bias', 'model.layers.22.linear_attn.A_log', 'model.layers.22.linear_attn.conv1d.weight', 'model.layers.22.linear_attn.norm.weight', 'model.layers.22.linear_attn.out_proj.weight', 'model.layers.22.linear_attn.in_proj_qkv.weight', 'model.layers.22.linear_attn.in_proj_z.weight', 'model.layers.22.linear_attn.in_proj_b.weight', 'model.layers.22.linear_attn.in_proj_a.weight', 'model.layers.22.mlp.gate_proj.weight', 'model.layers.22.mlp.up_proj.weight', 'model.layers.22.mlp.down_proj.weight', 'model.layers.22.input_layernorm.weight', 'model.layers.22.post_attention_layernorm.weight', 'model.layers.23.self_attn.q_proj.weight', 'model.layers.23.self_attn.k_proj.weight', 'model.layers.23.self_attn.v_proj.weight', 'model.layers.23.self_attn.o_proj.weight', 'model.layers.23.self_attn.q_norm.weight', 'model.layers.23.self_attn.k_norm.weight', 'model.layers.23.mlp.gate_proj.weight', 'model.layers.23.mlp.up_proj.weight', 'model.layers.23.mlp.down_proj.weight', 'model.layers.23.input_layernorm.weight', 'model.layers.23.post_attention_layernorm.weight', 'model.norm.weight', 'lm_head.weight'].

## step-9: 模型评估

In [25]:
evaluating_result = trainer.evaluate()
# testing_result = trainer.evaluate(dataset_test)
pp(evaluating_result)

{'eval_loss': 0.809271514415741,
 'eval_entropy': 0.6006145656108857,
 'eval_num_tokens': 12774.0,
 'eval_mean_token_accuracy': 0.7901647686958313}

## step-10: 模型保存

In [26]:
checkpoint_output = checkpoint + "-FFT"
path_output_inside = os.path.join(path_output, checkpoint_output)
os.makedirs(path_output_inside, exist_ok=True)

In [28]:
trainer.save_model(output_dir=path_output_inside)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:04<00:00,  4.42s/it]

## step-11: 模型推理

In [36]:
user_prompt = train_dataset[0]["instruction"] + "\n" + train_dataset[0]["input"]

messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]

In [37]:
# 方法-1
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True  # inference
)
model_inputs = tokenizer([text], return_tensors="pt").to(device)
# model_inputs = tokenizer([text1, text2], return_tensors="pt", padding=True, truncation=True).to(device)

In [ ]:
# 方法-2
# model_inputs = tokenizer.apply_chat_template(
#     messages,
#     tokenize=True,
#     add_generation_prompt=True,
#     return_tensors="pt",
#     return_dict=True
# ).to(device)

In [49]:
# max_new_tokens = 1024  # 取训练样本答案的最长值
# top_p = 0.9
# temperature = 0.1  # 0.5，0.35，0.1，0.01
# # repetition_penalty = 1.5
gen_kwargs = {
    "max_new_tokens": 1024,  # 取训练样本答案的最长值
    "top_p": 0.5,
    "temperature": 0.5,  # 0.5，0.35，0.1，0.01
    "do_sample": True
}

In [52]:
# inference 模板
t0 = pd.Timestamp.now()
base_model.eval()
with th.inference_mode():
    complete_ids = base_model.generate(
        input_ids=model_inputs.input_ids,  # 针对 tokenizer.padding_side
        attention_mask=model_inputs.attention_mask,  # 针对 tokenizer.padding_side
        **gen_kwargs
    )
    # also OK
    # complete_ids = model_sft.generate(
    #     **model_inputs,  # 针对 tokenizer.padding_side
    #     **gen_kwargs
    # )
t1 = pd.Timestamp.now()
print(t1 - t0)

input_ids = model_inputs.input_ids
generated_ids = [O[len(I): ] for (I, O) in zip(input_ids, complete_ids)]
response = tokenizer.batch_decode(sequences=generated_ids, skip_special_tokens=True)[0]
print(response)

0 days 00:00:00.721776
The total surface area of a cube is 150 cm².

In [40]:
train_dataset[0]["output"]

'Total surface area of the cube: 150 cm^2'